URL_SHORTENERS = (
    "tinyurl.com", "bit.ly", "rb.gy", "is.gd", "t.co", "goo.gl", "ow.ly", "buff.ly", "adf.ly", "bit.do", "cutt.ly",
    "shorturl.at", "shorte.st", "rebrand.ly", "cli.re", "soo.gd", "chilp.it", "x.co", "lc.chat", "qr.ae", "lnkd.in",
    "lnk.to", "smarturl.it", "s.id", "u.to", "v.gd", "po.st", "linktr.ee", "plu.sh", "lnk.bio", "t.ly", "tiny.cc",
    "shrtco.de", "yourls.org", "bl.ink", "sk.gy", "bitly.ws", "gg.gg", "short.cm", "hive.am", "urlzs.com", "adfoc.us",
    "ouo.io", "clicky.me", "tny.im", "up.ht", "ift.tt", "dlvr.it", "trib.al", "snip.ly", "2.gp", "vzturl.com",
    "shrinke.me", "bc.vc", "exe.io", "t2m.io", "viralurl.com", "short.io", "thinfi.com", "adcrun.ch", "clk.im",
    "dzurl.ml", "tiny.lt", "lnkfi.re", "lihi.cc", "ity.im", "short.cm", "qps.ru", "hyperurl.co", "shr.tn",
    "tiny.pl", "miniurl.io", "4url.cc", "cutwi.in", "bitly.com", "tlnk.io", "zzb.bz", "fy.cx", "rb6.co", "cocoleech.com",
    "clickmeter.com", "cur.lv", "mcaf.ee", "tmblr.co", "snipurl.com", "budurl.com", "capsulink.com", "admy.link",
    "b.link", "mshort.link", "t9y.me", "surl.li", "urlr.me", "shr.lc", "scrnch.me", "tr.im", "0rz.tw", "yep.it",
    "2ty.cc", "smrl.io", "hmm.ph", "micurl.com", "shorties.io", "soo.ny", "clicky.me", "pd.am", "v.gd", "bitw.in",
    "xurl.es", "url.ie", "lttr.ai", "cut.pe", "cutwin.com", "me2.do", "lnk.sk", "dlvrit.com", "jmp.sh", "tcrn.ch",
    "hex.pm", "lnk.sg", "go2l.ink", "afly.co", "clickto.at", "sohoo.me", "shr.re", "urlcloud.us", "1url.com",
    "tiny.cc", "coco.ly", "tiiny.site", "atominik.com", "buzzurl.jp", "shorturl.gg", "picsee.io", "1drv.ms", "ht.ly",
    "zip.net", "quickurl.cc", "tiny.ie", "shrnk.link", "hive.am", "updog.co", "tlink.io", "tlink.cc", "roflc.at",
    "tr5.in", "go0.co", "icn.li", "to.ly", "smarturl.lnk", "snip.so", "clk.sh", "stfly.io", "rclink.net", "tmx.me",
    "shorter.me", "p.pw", "adcraft.co", "snpurl.com", "shar.as", "r.im", "linkn.co", "linku.at", "viralurl.com",
    "shorten.asia", "cort.as", "shrinke.net", "tiny.click", "shrinkme.io", "adsafelink.com", "miniurl.net", "2no.co",
    "5z8.info", "ou.af", "zip.net", "urlcorta.es", "alturl.com", "ix.sk", "s9w.io", "abr.li", "9nl.es", "0x0.st",
    "8bit.co", "krunchd.com", "flq.us", "budurl.me", "bacn.me", "buzzurl.jp", "linkshrink.net", "admy.link",
    "viralurl.net", "linkgenie.me", "shorte.link", "mcaf.ee", "mrk.li", "tweaklinks.com", "vzturl.com", "cutl.ly",
    "cut-urls.com", "1short.us", "smarurl.com", "go.gl", "rdlnk.io", "vip.li", "miny.cc", "n9.cl", "rb6.co",
    "cu2.io", "tl.gd", "grabify.link", "gyazo.me", "ne1.net", "tini.cc", "ex9.co", "rbn.co", "zpr.io"
)